export const allTeamsMaps = {
  '0': {
    teamID: 0,
    label: 'Buffalo Stampede',
    city: 'Buffalo',
    team: 'Stampede',
    abbreviation: 'BUF',
    league: 'SHL',
    conference: 'East',
  },
  '1': {
    teamID: 1,
    label: 'Chicago Syndicate',
    city: 'Chicago',
    team: 'Syndicate',
    abbreviation: 'CHI',
    league: 'SHL',
    conference: 'East',
  },
  '2': {
    teamID: 2,
    label: 'Hamilton Steelhawks',
    city: 'Hamilton',
    team: 'Steelhawks',
    abbreviation: 'HAM',
    league: 'SHL',
    conference: 'East',
  },
  '3': {
    teamID: 3,
    label: 'Toronto North Stars',
    city: 'Toronto',
    team: 'North Stars',
    abbreviation: 'TOR',
    league: 'SHL',
    conference: 'East',
  },
  '4': {
    teamID: 4,
    label: 'Manhattan Rage',
    city: 'Manhattan',
    team: 'Rage',
    abbreviation: 'MAN',
    league: 'SHL',
    conference: 'East',
  },
  '5': {
    teamID: 5,
    label: 'New England Wolfpack',
    city: 'New England',
    team: 'Wolfpack',
    abbreviation: 'NEW',
    league: 'SHL',
    conference: 'East',
  },
  '6': {
    teamID: 6,
    label: 'Tampa Bay Barracuda',
    city: 'Tampa Bay',
    team: 'Barracuda',
    abbreviation: 'TBB',
    league: 'SHL',
    conference: 'East',
  },
  '7': {
    teamID: 7,
    label: 'Baltimore Platoon',
    city: 'Baltimore',
    team: 'Platoon',
    abbreviation: 'BAP',
    league: 'SHL',
    conference: 'East',
  },
  '8': {
    teamID: 8,
    label: 'Calgary Dragons',
    city: 'Calgary',
    team: 'Dragons',
    abbreviation: 'CGY',
    league: 'SHL',
    conference: 'West',
  },
  '9': {
    teamID: 9,
    label: 'Edmonton Blizzard',
    city: 'Edmonton',
    team: 'Blizzard',
    abbreviation: 'EDM',
    league: 'SHL',
    conference: 'West',
  },
  '10': {
    teamID: 10,
    label: 'Minnesota Monarchs',
    city: 'Minnesota',
    team: 'Monarchs',
    abbreviation: 'MIN',
    league: 'SHL',
    conference: 'West',
  },
  '11': {
    teamID: 11,
    label: 'Winnipeg Aurora',
    city: 'Winnipeg',
    team: 'Aurora',
    abbreviation: 'WPG',
    league: 'SHL',
    conference: 'West',
  },
  '12': {
    teamID: 12,
    label: 'San Francisco Pride',
    city: 'San Francisco',
    team: 'Pride',
    abbreviation: 'SFP',
    league: 'SHL',
    conference: 'West',
  },
  '13': {
    teamID: 13,
    label: 'Los Angeles Panthers',
    city: 'Los Angeles',
    team: 'Panthers',
    abbreviation: 'LAP',
    league: 'SHL',
    conference: 'West',
  },
  '14': {
    teamID: 14,
    label: 'New Orleans Specters',
    city: 'New Orleans',
    team: 'Specters',
    abbreviation: 'NOLA',
    league: 'SHL',
    conference: 'West',
  },
  '15': {
    teamID: 15,
    label: 'Texas Renegades',
    city: 'Texas',
    team: 'Renegades',
    abbreviation: 'TEX',
    league: 'SHL',
    conference: 'West',
  },
  '18': {
    teamID: 18,
    label: 'Atlanta Inferno',
    city: 'Atlanta',
    team: 'Inferno',
    abbreviation: 'ATL',
    league: 'SHL',
    conference: 'East',
  },
  '19': {
    teamID: 19,
    label: 'Seattle Argonauts',
    city: 'Seattle',
    team: 'Argonauts',
    abbreviation: 'SEA',
    league: 'SHL',
    conference: 'West',
  },
  '20': {
    teamID: 20,
    label: 'Montreal Patriotes',
    city: 'Montreal',
    team: 'Patriotes',
    abbreviation: 'MTL',
    league: 'SHL',
    conference: 'East',
  },
  '21': {
    teamID: 21,
    label: 'Philadelphia Forge',
    city: 'Philadelphia',
    team: 'Forge',
    abbreviation: 'PHI',
    league: 'SHL',
    conference: 'East',
  },
  '22': {
    teamID: 0,
    label: 'Germany',
    city: 'Germany',
    team: null,
    abbreviation: 'GER',
    league: 'IIHF',
    conference: null,
  },
  '23': {
    teamID: 1,
    label: 'Great Britain',
    city: 'Great Britain',
    team: null,
    abbreviation: 'GBR',
    league: 'IIHF',
    conference: null,
  },
  '24': {
    teamID: 2,
    label: 'Ireland',
    city: 'Ireland',
    team: null,
    abbreviation: 'IRE',
    league: 'IIHF',
    conference: null,
  },
  '25': {
    teamID: 4,
    label: 'France',
    city: 'France',
    team: null,
    abbreviation: 'FRA',
    league: 'IIHF',
    conference: null,
  },
  '26': {
    teamID: 5,
    label: 'Canada',
    city: 'Canada',
    team: null,
    abbreviation: 'CAN',
    league: 'IIHF',
    conference: null,
  },
  '27': {
    teamID: 6,
    label: 'Czechia',
    city: 'Czechia',
    team: null,
    abbreviation: 'CZE',
    league: 'IIHF',
    conference: null,
  },
  '28': {
    teamID: 7,
    label: 'Finland',
    city: 'Finland',
    team: null,
    abbreviation: 'FIN',
    league: 'IIHF',
    conference: null,
  },
  '29': {
    teamID: 8,
    label: 'Quebec',
    city: 'Quebec',
    team: null,
    abbreviation: 'QC',
    league: 'IIHF',
    conference: null,
  },
  '30': {
    teamID: 9,
    label: 'Sweden',
    city: 'Sweden',
    team: null,
    abbreviation: 'SWE',
    league: 'IIHF',
    conference: null,
  },
  '31': {
    teamID: 10,
    label: 'Switzerland',
    city: 'Switzerland',
    team: null,
    abbreviation: 'SWI',
    league: 'IIHF',
    conference: null,
  },
  '32': {
    teamID: 11,
    label: 'United States',
    city: 'United States',
    team: null,
    abbreviation: 'USA',
    league: 'IIHF',
    conference: null,
  },
  '33': {
    teamID: 12,
    label: 'Japan',
    city: 'Japan',
    team: null,
    abbreviation: 'JPN',
    league: 'IIHF',
    conference: null,
  },
  '34': {
    teamID: 13,
    label: 'Latvia',
    city: 'Latvia',
    team: null,
    abbreviation: 'LTV',
    league: 'IIHF',
    conference: null,
  },
  '35': {
    teamID: 14,
    label: 'Norway',
    city: 'Norway',
    team: null,
    abbreviation: 'NOR',
    league: 'IIHF',
    conference: null,
  },
  '36': {
    teamID: 22,
    label: 'Cincinnati Six',
    city: 'Cincinnati',
    team: 'Six',
    abbreviation: 'CIN',
    league: 'SHL',
    conference: 'East',
  },
  '37': {
    teamID: 23,
    label: 'Nashville Sound',
    city: 'Nashville',
    team: 'Sound',
    abbreviation: 'NSH',
    league: 'SHL',
    conference: 'East',
  },
  '38': {
    teamID: 24,
    label: 'Denver Glacier Guardians',
    city: 'Denver',
    team: 'Glacier Guardians',
    abbreviation: 'DEN',
    league: 'SHL',
    conference: 'West',
  },
  '39': {
    teamID: 25,
    label: 'Madison Valkyries',
    city: 'Madison',
    team: 'Valkyries',
    abbreviation: 'MAD',
    league: 'SHL',
    conference: 'West',
  },
}

export const iihfTeamsMap = {
  '0': {
    teamID: 0,
    label: 'Germany',
    city: 'Germany',
    team: null,
    abbreviation: 'GER',
    league: 'IIHF',
    conference: null,
  },
  '1': {
    teamID: 1,
    label: 'Great Britain',
    city: 'Great Britain',
    team: null,
    abbreviation: 'GBR',
    league: 'IIHF',
    conference: null,
  },
  '2': {
    teamID: 2,
    label: 'Ireland',
    city: 'Ireland',
    team: null,
    abbreviation: 'IRE',
    league: 'IIHF',
    conference: null,
  },
  '4': {
    teamID: 4,
    label: 'France',
    city: 'France',
    team: null,
    abbreviation: 'FRA',
    league: 'IIHF',
    conference: null,
  },
  '5': {
    teamID: 5,
    label: 'Canada',
    city: 'Canada',
    team: null,
    abbreviation: 'CAN',
    league: 'IIHF',
    conference: null,
  },
  '6': {
    teamID: 6,
    label: 'Czechia',
    city: 'Czechia',
    team: null,
    abbreviation: 'CZE',
    league: 'IIHF',
    conference: null,
  },
  '7': {
    teamID: 7,
    label: 'Finland',
    city: 'Finland',
    team: null,
    abbreviation: 'FIN',
    league: 'SHL',
    conference: null,
  },
  '8': {
    teamID: 8,
    label: 'Quebec',
    city: 'Quebec',
    team: null,
    abbreviation: 'QC',
    league: 'IIHF',
    conference: null,
  },
  '9': {
    teamID: 9,
    label: 'Sweden',
    city: 'Sweden',
    team: null,
    abbreviation: 'SWE',
    league: 'IIHF',
    conference: null,
  },
  '10': {
    teamID: 10,
    label: 'Switzerland',
    city: 'Switzerland',
    team: null,
    abbreviation: 'SWI',
    league: 'IIHF',
    conference: null,
  },
  '11': {
    teamID: 11,
    label: 'United States',
    city: 'United States',
    team: null,
    abbreviation: 'USA',
    league: 'IIHF',
    conference: null,
  },
  '12': {
    teamID: 12,
    label: 'Japan',
    city: 'Japan',
    team: null,
    abbreviation: 'JPN',
    league: 'IIHF',
    conference: null,
  },
  '13': {
    teamID: 13,
    label: 'Latvia',
    city: 'Latvia',
    team: null,
    abbreviation: 'LTV',
    league: 'IIHF',
    conference: null,
  },
  '14': {
    teamID: 14,
    label: 'Norway',
    city: 'Norway',
    team: null,
    abbreviation: 'NOR',
    league: 'IIHF',
    conference: null,
  },
}

export const shlTeamMap = {
  '0': {
    teamID: 0,
    label: 'Buffalo Stampede',
    city: 'Buffalo',
    team: 'Stampede',
    abbreviation: 'BUF',
    league: 'SHL',
    conference: 'East',
  },
  '1': {
    teamID: 1,
    label: 'Chicago Syndicate',
    city: 'Chicago',
    team: 'Syndicate',
    abbreviation: 'CHI',
    league: 'SHL',
    conference: 'East',
  },
  '2': {
    teamID: 2,
    label: 'Hamilton Steelhawks',
    city: 'Hamilton',
    team: 'Steelhawks',
    abbreviation: 'HAM',
    league: 'SHL',
    conference: 'East',
  },
  '3': {
    teamID: 3,
    label: 'Toronto North Stars',
    city: 'Toronto',
    team: 'North Stars',
    abbreviation: 'TOR',
    league: 'SHL',
    conference: 'East',
  },
  '4': {
    teamID: 4,
    label: 'Manhattan Rage',
    city: 'Manhattan',
    team: 'Rage',
    abbreviation: 'MAN',
    league: 'SHL',
    conference: 'East',
  },
  '5': {
    teamID: 5,
    label: 'New England Wolfpack',
    city: 'New England',
    team: 'Wolfpack',
    abbreviation: 'NEW',
    league: 'SHL',
    conference: 'East',
  },
  '6': {
    teamID: 6,
    label: 'Tampa Bay Barracuda',
    city: 'Tampa Bay',
    team: 'Barracuda',
    abbreviation: 'TBB',
    league: 'SHL',
    conference: 'East',
  },
  '7': {
    teamID: 7,
    label: 'Baltimore Platoon',
    city: 'Baltimore',
    team: 'Platoon',
    abbreviation: 'BAP',
    league: 'SHL',
    conference: 'East',
  },
  '8': {
    teamID: 8,
    label: 'Calgary Dragons',
    city: 'Calgary',
    team: 'Dragons',
    abbreviation: 'CGY',
    league: 'SHL',
    conference: 'West',
  },
  '9': {
    teamID: 9,
    label: 'Edmonton Blizzard',
    city: 'Edmonton',
    team: 'Blizzard',
    abbreviation: 'EDM',
    league: 'SHL',
    conference: 'West',
  },
  '10': {
    teamID: 10,
    label: 'Minnesota Monarchs',
    city: 'Minnesota',
    team: 'Monarchs',
    abbreviation: 'MIN',
    league: 'SHL',
    conference: 'West',
  },
  '11': {
    teamID: 11,
    label: 'Winnipeg Aurora',
    city: 'Winnipeg',
    team: 'Aurora',
    abbreviation: 'WPG',
    league: 'SHL',
    conference: 'West',
  },
  '12': {
    teamID: 12,
    label: 'San Francisco Pride',
    city: 'San Francisco',
    team: 'Pride',
    abbreviation: 'SFP',
    league: 'SHL',
    conference: 'West',
  },
  '13': {
    teamID: 13,
    label: 'Los Angeles Panthers',
    city: 'Los Angeles',
    team: 'Panthers',
    abbreviation: 'LAP',
    league: 'SHL',
    conference: 'West',
  },
  '14': {
    teamID: 14,
    label: 'New Orleans Specters',
    city: 'New Orleans',
    team: 'Specters',
    abbreviation: 'NOLA',
    league: 'SHL',
    conference: 'West',
  },
  '15': {
    teamID: 15,
    label: 'Texas Renegades',
    city: 'Texas',
    team: 'Renegades',
    abbreviation: 'TEX',
    league: 'SHL',
    conference: 'West',
  },
  '18': {
    teamID: 18,
    label: 'Atlanta Inferno',
    city: 'Atlanta',
    team: 'Inferno',
    abbreviation: 'ATL',
    league: 'SHL',
    conference: 'East',
  },
  '19': {
    teamID: 19,
    label: 'Seattle Argonauts',
    city: 'Seattle',
    team: 'Argonauts',
    abbreviation: 'SEA',
    league: 'SHL',
    conference: 'West',
  },
  '20': {
    teamID: 20,
    label: 'Montreal Patriotes',
    city: 'Montreal',
    team: 'Patriotes',
    abbreviation: 'MTL',
    league: 'SHL',
    conference: 'East',
  },
  '21': {
    teamID: 21,
    label: 'Philadelphia Forge',
    city: 'Philadelphia',
    team: 'Forge',
    abbreviation: 'PHI',
    league: 'SHL',
    conference: 'East',
  },
  '22': {
    teamID: 22,
    label: 'Cincinnati Six',
    city: 'Cincinnati',
    team: 'Six',
    abbreviation: 'CIN',
    league: 'SHL',
    conference: 'East',
  },
  '23': {
    teamID: 23,
    label: 'Nashville Sound',
    city: 'Nashville',
    team: 'Sound',
    abbreviation: 'NSH',
    league: 'SHL',
    conference: 'East',
  },
  '24': {
    teamID: 24,
    label: 'Denver Glacier Guardians',
    city: 'Denver',
    team: 'Glacier Guardians',
    abbreviation: 'DEN',
    league: 'SHL',
    conference: 'West',
  },
  '25': {
    teamID: 25,
    label: 'Madison Valkyries',
    city: 'Madison',
    team: 'Valkyries',
    abbreviation: 'MAD',
    league: 'SHL',
    conference: 'West',
  },
}
