const { fontFamily } = require('tailwindcss/defaultTheme')

module.exports = {
  mode: 'jit',
  important: true,
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './tailwind-components/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: ['class', '.chakra-ui-dark'],
  content: ['./pages/**/*.tsx', './components/**/*.tsx'],
  theme: {
    colors: {
      hyperlink: 'rgba(var(--hyperlink))',
      hyperlinkDark: 'rgba(var(--hyperlinkDark))',
      borderblue: 'rgba(var(--borderblue))',
      borderblueDark: 'rgba(var(--borderblueDark))',
      darkerBorderBlue: 'rgba(var(--darkerBorderBlue))',
      darkerBorderBlueDark: 'rgba(var(--darkerBorderBlueDark))',
      primary: 'rgba(var(--primary))',
      primaryDark: 'rgba(var(--primaryDark))',
      LabelHeadings: 'rgba(var(--LabelHeadings))',
      LabelHeadingsDark: 'rgba(var(--LabelHeadingsDark))',
      tpeChart: 'rgba(var(--tpeChart))',
      tpeChartDark: 'rgba(var(--tpeChartDark))',
      commonSubHeading: 'rgba(var(--commonSubHeading))',
      commonSubHeadingDark: 'rgba(var(--commonSubHeadingDark))',
      sudoButton: 'rgba(var(--sudoButton))',
      sudoButtonDark: 'rgba(var(--sudoButtonDark))',
      boxborder: 'rgba(var(--boxborder))',
      boxborderDark: 'rgba(var(--boxborderDark))',
      hoverSelect: 'rgba(var(--hoverSelect))',
      hoverSelectDark: 'rgba(var(--hoverSelectDark))',
      attributeUnderline: 'rgba(var(--attributeUnderline))',
      attributeUnderlineDark: 'rgba(var(--attributeUnderlineDark))',
      alternatedColor: 'rgba(var(--alternatedColor))',
      alternatedColorDark: 'rgba(var(--alternatedColorDark))',
      secondary: 'rgba(var(--secondary))',
      secondaryDark: 'rgba(var(--secondaryDark))',
      secondaryText: 'rgba(var(--secondaryText))',
      secondaryTextDark: 'rgba(var(--secondaryTextDark))',
      red: 'rgba(var(--red))',
      redDark: 'rgba(var(--redDark))',
      offWhite: 'rgba(var(--offWhite))',
    },
    fontFamily: {
      raleway: ['var(--font-raleway)', ...fontFamily.sans],
      mont: ['var(--font-montserrat)', ...fontFamily.sans],
    },
    extend: {
      fontSize: {
        xxsm: '0.6rem',
      },
    },
  },
  plugins: [],
}
