import { Lineup } from '../../index.d'

const getLineup = (teamCards: Card[]): Lineup => {
  return {
    center_1: {
      playerID: teamCards[0].playerID,
      player_name: teamCards[0].player_name,
      position: teamCards[0].position,
      card_rarity: teamCards[0].card_rarity,
      overall: teamCards[0].overall,
      skating: teamCards[0].skating,
      shooting: teamCards[0].shooting,
      hands: teamCards[0].hands,
      checking: teamCards[0].checking,
      defense: teamCards[0].defense,
    },
    center_2: {
      playerID: teamCards[1].playerID,
      player_name: teamCards[1].player_name,
      position: teamCards[1].position,
      card_rarity: teamCards[1].card_rarity,
      overall: teamCards[1].overall,
      skating: teamCards[1].skating,
      shooting: teamCards[1].shooting,
      hands: teamCards[1].hands,
      checking: teamCards[1].checking,
      defense: teamCards[1].defense,
    },
    center_3: {
      playerID: teamCards[2].playerID,
      player_name: teamCards[2].player_name,
      position: teamCards[2].position,
      card_rarity: teamCards[2].card_rarity,
      overall: teamCards[2].overall,
      skating: teamCards[2].skating,
      shooting: teamCards[2].shooting,
      hands: teamCards[2].hands,
      checking: teamCards[2].checking,
      defense: teamCards[2].defense,
    },
    center_4: {
      playerID: teamCards[3].playerID,
      player_name: teamCards[3].player_name,
      position: teamCards[3].position,
      card_rarity: teamCards[3].card_rarity,
      overall: teamCards[3].overall,
      skating: teamCards[3].skating,
      shooting: teamCards[3].shooting,
      hands: teamCards[3].hands,
      checking: teamCards[3].checking,
      defense: teamCards[3].defense,
    },
    leftWing_1: {
      playerID: teamCards[4].playerID,
      player_name: teamCards[4].player_name,
      position: teamCards[4].position,
      card_rarity: teamCards[4].card_rarity,
      overall: teamCards[4].overall,
      skating: teamCards[4].skating,
      shooting: teamCards[4].shooting,
      hands: teamCards[4].hands,
      checking: teamCards[4].checking,
      defense: teamCards[4].defense,
    },
    leftWing_2: {
      playerID: teamCards[5].playerID,
      player_name: teamCards[5].player_name,
      position: teamCards[5].position,
      card_rarity: teamCards[5].card_rarity,
      overall: teamCards[5].overall,
      skating: teamCards[5].skating,
      shooting: teamCards[5].shooting,
      hands: teamCards[5].hands,
      checking: teamCards[5].checking,
      defense: teamCards[5].defense,
    },
    leftWing_3: {
      playerID: teamCards[6].playerID,
      player_name: teamCards[6].player_name,
      position: teamCards[6].position,
      card_rarity: teamCards[6].card_rarity,
      overall: teamCards[6].overall,
      skating: teamCards[6].skating,
      shooting: teamCards[6].shooting,
      hands: teamCards[6].hands,
      checking: teamCards[6].checking,
      defense: teamCards[6].defense,
    },
    leftWing_4: {
      playerID: teamCards[7].playerID,
      player_name: teamCards[7].player_name,
      position: teamCards[7].position,
      card_rarity: teamCards[7].card_rarity,
      overall: teamCards[7].overall,
      skating: teamCards[7].skating,
      shooting: teamCards[7].shooting,
      hands: teamCards[7].hands,
      checking: teamCards[7].checking,
      defense: teamCards[7].defense,
    },
    rightWing_1: {
      playerID: teamCards[8].playerID,
      player_name: teamCards[8].player_name,
      position: teamCards[8].position,
      card_rarity: teamCards[8].card_rarity,
      overall: teamCards[8].overall,
      skating: teamCards[8].skating,
      shooting: teamCards[8].shooting,
      hands: teamCards[8].hands,
      checking: teamCards[8].checking,
      defense: teamCards[8].defense,
    },
    rightWing_2: {
      playerID: teamCards[9].playerID,
      player_name: teamCards[9].player_name,
      position: teamCards[9].position,
      card_rarity: teamCards[9].card_rarity,
      overall: teamCards[9].overall,
      skating: teamCards[9].skating,
      shooting: teamCards[9].shooting,
      hands: teamCards[9].hands,
      checking: teamCards[9].checking,
      defense: teamCards[9].defense,
    },
    rightWing_3: {
      playerID: teamCards[10].playerID,
      player_name: teamCards[10].player_name,
      position: teamCards[10].position,
      card_rarity: teamCards[10].card_rarity,
      overall: teamCards[10].overall,
      skating: teamCards[10].skating,
      shooting: teamCards[10].shooting,
      hands: teamCards[10].hands,
      checking: teamCards[10].checking,
      defense: teamCards[10].defense,
    },
    rightWing_4: {
      playerID: teamCards[11].playerID,
      player_name: teamCards[11].player_name,
      position: teamCards[11].position,
      card_rarity: teamCards[11].card_rarity,
      overall: teamCards[11].overall,
      skating: teamCards[11].skating,
      shooting: teamCards[11].shooting,
      hands: teamCards[11].hands,
      checking: teamCards[11].checking,
      defense: teamCards[11].defense,
    },
    leftDefense_1: {
      playerID: teamCards[12].playerID,
      player_name: teamCards[12].player_name,
      position: teamCards[12].position,
      card_rarity: teamCards[12].card_rarity,
      overall: teamCards[12].overall,
      skating: teamCards[12].skating,
      shooting: teamCards[12].shooting,
      hands: teamCards[12].hands,
      checking: teamCards[12].checking,
      defense: teamCards[12].defense,
    },
    leftDefense_2: {
      playerID: teamCards[13].playerID,
      player_name: teamCards[13].player_name,
      position: teamCards[13].position,
      card_rarity: teamCards[13].card_rarity,
      overall: teamCards[13].overall,
      skating: teamCards[13].skating,
      shooting: teamCards[13].shooting,
      hands: teamCards[13].hands,
      checking: teamCards[13].checking,
      defense: teamCards[13].defense,
    },
    leftDefense_3: {
      playerID: teamCards[14].playerID,
      player_name: teamCards[14].player_name,
      position: teamCards[14].position,
      card_rarity: teamCards[14].card_rarity,
      overall: teamCards[14].overall,
      skating: teamCards[14].skating,
      shooting: teamCards[14].shooting,
      hands: teamCards[14].hands,
      checking: teamCards[14].checking,
      defense: teamCards[14].defense,
    },
    rightDefense_1: {
      playerID: teamCards[15].playerID,
      player_name: teamCards[15].player_name,
      position: teamCards[15].position,
      card_rarity: teamCards[15].card_rarity,
      overall: teamCards[15].overall,
      skating: teamCards[15].skating,
      shooting: teamCards[15].shooting,
      hands: teamCards[15].hands,
      checking: teamCards[15].checking,
      defense: teamCards[15].defense,
    },
    rightDefense_2: {
      playerID: teamCards[16].playerID,
      player_name: teamCards[16].player_name,
      position: teamCards[16].position,
      card_rarity: teamCards[16].card_rarity,
      overall: teamCards[16].overall,
      skating: teamCards[16].skating,
      shooting: teamCards[16].shooting,
      hands: teamCards[16].hands,
      checking: teamCards[16].checking,
      defense: teamCards[16].defense,
    },
    rightDefense_3: {
      playerID: teamCards[17].playerID,
      player_name: teamCards[17].player_name,
      position: teamCards[17].position,
      card_rarity: teamCards[17].card_rarity,
      overall: teamCards[17].overall,
      skating: teamCards[17].skating,
      shooting: teamCards[17].shooting,
      hands: teamCards[17].hands,
      checking: teamCards[17].checking,
      defense: teamCards[17].defense,
    },
    goalie_1: {
      playerID: teamCards[18].playerID,
      player_name: teamCards[18].player_name,
      position: teamCards[18].position,
      card_rarity: teamCards[18].card_rarity,
      overall: teamCards[18].overall,
      high_shots: teamCards[18].skating,
      low_shots: teamCards[18].shooting,
      quickness: teamCards[18].hands,
      control: teamCards[18].checking,
      conditioning: teamCards[18].defense,
    },
    goalie_2: {
      playerID: teamCards[19].playerID,
      player_name: teamCards[19].player_name,
      position: teamCards[19].position,
      card_rarity: teamCards[19].card_rarity,
      overall: teamCards[19].overall,
      high_shots: teamCards[19].skating,
      low_shots: teamCards[19].shooting,
      quickness: teamCards[19].hands,
      control: teamCards[19].checking,
      conditioning: teamCards[19].defense,
    },
  }
}

export default getLineup
