const Teams = {
  Atlanta: {
    City: 'Atlanta',
    Team: 'Inferno',
    Abbreviation: 'ATL',
    League: 'SHL',
    Conference: 'East',
  },
  Baltimore: {
    City: 'Baltimore',
    Team: 'Platoon',
    Abbreviation: 'BAL',
    League: 'SHL',
    Conference: 'East',
  },
  Buffalo: {
    City: 'Buffalo',
    Team: 'Stampede',
    Abbreviation: 'BUF',
    League: 'SHL',
    Conference: 'East',
  },
  Chicago: {
    City: 'Chicago',
    Team: 'Syndicate',
    Abbreviation: 'CHI',
    League: 'SHL',
    Conference: 'East',
  },
  Hamilton: {
    City: 'Hamilton',
    Team: 'Steelhawks',
    Abbreviation: 'HAM',
    League: 'SHL',
    Conference: 'East',
  },
  Manhattan: {
    City: 'Manhattan',
    Team: 'Rage',
    Abbreviation: 'MAN',
    League: 'SHL',
    Conference: 'East',
  },
  NewEngland: {
    City: 'New England',
    Team: 'Wolfpack',
    Abbreviation: 'NEW',
    League: 'SHL',
    Conference: 'East',
  },
  TampaBay: {
    City: 'Tampa Bay',
    Team: 'Barracudua',
    Abbreviation: 'TBB',
    League: 'SHL',
    Conference: 'East',
  },
  Toronto: {
    City: 'Toronto',
    Team: 'North Stars',
    Abbreviation: 'TOR',
    League: 'SHL',
    Conference: 'East',
  },
  Calgary: {
    City: 'Calgary',
    Team: 'Dragons',
    Abbreviation: 'CAL',
    League: 'SHL',
    Conference: 'West',
  },
  Edmonton: {
    City: 'Edmonton',
    Team: 'Blizzard',
    Abbreviation: 'EDM',
    League: 'SHL',
    Conference: 'West',
  },
  LosAngeles: {
    City: 'Los Angeles',
    Team: 'Panthers',
    Abbreviation: 'LAP',
    League: 'SHL',
    Conference: 'West',
  },
  Minnesota: {
    City: 'Minnesota',
    Team: 'Monarchs',
    Abbreviation: 'MIN',
    League: 'SHL',
    Conference: 'West',
  },
  NewOrleans: {
    City: 'New Orleans',
    Team: 'Specters',
    Abbreviation: 'NOLA',
    League: 'SHL',
    Conference: 'West',
  },
  SanFrancisco: {
    City: 'San Francisco',
    Team: 'Pride',
    Abbreviation: 'SFP',
    League: 'SHL',
    Conference: 'West',
  },
  Seattle: {
    City: 'Seattle',
    Team: 'Argonauts',
    Abbreviation: 'SEA',
    League: 'SHL',
    Conference: 'West',
  },
  Texas: {
    City: 'Texas',
    Team: 'Renegades',
    Abbreviation: 'TEX',
    League: 'SHL',
    Conference: 'West',
  },
  Winnipeg: {
    City: 'Winnipeg',
    Team: 'Aurora',
    Abbreviation: 'WPG',
    League: 'SHL',
    Conference: 'West',
  },
  Anaheim: {
    City: 'Anaheim',
    Team: 'Outlaws',
    Abbreviation: 'ANA',
    League: 'SMJHL',
    Conference: 'SMJHL',
  },
  Anchorage: {
    City: 'Anchorage',
    Team: 'Armada',
    Abbreviation: 'ANC',
    League: 'SMJHL',
    Conference: 'SMJHL',
  },
  Carolina: {
    City: 'Carolina',
    Team: 'Kraken',
    Abbreviation: 'CAR',
    League: 'SMJHL',
    Conference: 'SMJHL',
  },
  Colorado: {
    City: 'Colorado',
    Team: 'Raptors',
    Abbreviation: 'COL',
    League: 'SMJHL',
    Conference: 'SMJHL',
  },
  Detroit: {
    City: 'Detroit',
    Team: 'Falcons',
    Abbreviation: 'DET',
    League: 'SMJHL',
    Conference: 'SMJHL',
  },
  Kelowna: {
    City: 'Kelowna',
    Team: 'Knights',
    Abbreviation: 'KEL',
    League: 'SMJHL',
    Conference: 'SMJHL',
  },
  Maine: {
    City: 'Maine',
    Team: 'Timber',
    Abbreviation: 'MET',
    League: 'SMJHL',
    Conference: 'SMJHL',
  },
  Nevada: {
    City: 'Nevada',
    Team: 'Battleborn',
    Abbreviation: 'NBB',
    League: 'SMJHL',
    Conference: 'SMJHL',
  },
  Newfoundland: {
    City: 'Newfoundland',
    Team: 'Berserkers',
    Abbreviation: 'NL',
    League: 'SMJHL',
    Conference: 'SMJHL',
  },
  QuebecCity: {
    City: 'Quebec City',
    Team: 'Citadelles',
    Abbreviation: 'QCC',
    League: 'SMJHL',
    Conference: 'SMJHL',
  },
  StLouis: {
    City: 'St. Louis',
    Team: 'Scarecrows',
    Abbreviation: 'STL',
    League: 'SMJHL',
    Conference: 'SMJHL',
  },
  Vancouver: {
    City: 'Vancouver',
    Team: 'Whalers',
    Abbreviation: 'VAN',
    League: 'SMJHL',
    Conference: 'SMJHL',
  },
}

export default Teams
