const teams = {
  Atlanta: {
    city: 'Atlanta',
    team: 'Inferno',
    abbreviation: 'ATL',
    league: 'SHL',
    conference: 'East',
  },
  Baltimore: {
    city: 'Baltimore',
    team: 'Platoon',
    abbreviation: 'BAL',
    league: 'SHL',
    conference: 'East',
  },
  Buffalo: {
    city: 'Buffalo',
    team: 'Stampede',
    abbreviation: 'BUF',
    league: 'SHL',
    conference: 'East',
  },
  Chicago: {
    city: 'Chicago',
    team: 'Syndicate',
    abbreviation: 'CHI',
    league: 'SHL',
    conference: 'East',
  },
  Hamilton: {
    city: 'Hamilton',
    team: 'Steelhawks',
    abbreviation: 'HAM',
    league: 'SHL',
    conference: 'East',
  },
  Manhattan: {
    city: 'Manhattan',
    team: 'Rage',
    abbreviation: 'MAN',
    league: 'SHL',
    conference: 'East',
  },
  NewEngland: {
    city: 'New England',
    team: 'Wolfpack',
    abbreviation: 'NEW',
    league: 'SHL',
    conference: 'East',
  },
  TampaBay: {
    city: 'Tampa Bay',
    team: 'Barracudua',
    abbreviation: 'TBB',
    league: 'SHL',
    conference: 'East',
  },
  Toronto: {
    city: 'Toronto',
    team: 'North Stars',
    abbreviation: 'TOR',
    league: 'SHL',
    conference: 'East',
  },
  Calgary: {
    city: 'Calgary',
    team: 'Dragons',
    abbreviation: 'CAL',
    league: 'SHL',
    conference: 'West',
  },
  Edmonton: {
    city: 'Edmonton',
    team: 'Blizzard',
    abbreviation: 'EDM',
    league: 'SHL',
    conference: 'West',
  },
  LosAngeles: {
    city: 'Los Angeles',
    team: 'Panthers',
    abbreviation: 'LAP',
    league: 'SHL',
    conference: 'West',
  },
  Minnesota: {
    city: 'Minnesota',
    team: 'Monarchs',
    abbreviation: 'MIN',
    league: 'SHL',
    conference: 'West',
  },
  NewOrleans: {
    city: 'New Orleans',
    team: 'Specters',
    abbreviation: 'NOLA',
    league: 'SHL',
    conference: 'West',
  },
  SanFrancisco: {
    city: 'San Francisco',
    team: 'Pride',
    abbreviation: 'SFP',
    league: 'SHL',
    conference: 'West',
  },
  Seattle: {
    city: 'Seattle',
    team: 'Argonauts',
    abbreviation: 'SEA',
    league: 'SHL',
    conference: 'West',
  },
  Texas: {
    city: 'Texas',
    team: 'Renegades',
    abbreviation: 'TEX',
    league: 'SHL',
    conference: 'West',
  },
  Winnipeg: {
    city: 'Winnipeg',
    team: 'Aurora',
    abbreviation: 'WPG',
    league: 'SHL',
    conference: 'West',
  },
  Anaheim: {
    city: 'Anaheim',
    team: 'Outlaws',
    abbreviation: 'ANA',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  Anchorage: {
    city: 'Anchorage',
    team: 'Armada',
    abbreviation: 'ANC',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  Carolina: {
    city: 'Carolina',
    team: 'Kraken',
    abbreviation: 'CAR',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  Colorado: {
    city: 'Colorado',
    team: 'Raptors',
    abbreviation: 'COL',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  Detroit: {
    city: 'Detroit',
    team: 'Falcons',
    abbreviation: 'DET',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  Kelowna: {
    city: 'Kelowna',
    team: 'Knights',
    abbreviation: 'KEL',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  Maine: {
    city: 'Maine',
    team: 'Timber',
    abbreviation: 'MET',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  Nevada: {
    city: 'Nevada',
    team: 'Battleborn',
    abbreviation: 'NBB',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  Newfoundland: {
    city: 'Newfoundland',
    team: 'Berserkers',
    abbreviation: 'NL',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  QuebecCity: {
    city: 'Quebec City',
    team: 'Citadelles',
    abbreviation: 'QCC',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  StLouis: {
    city: 'St. Louis',
    team: 'Scarecrows',
    abbreviation: 'STL',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  Vancouver: {
    city: 'Vancouver',
    team: 'Whalers',
    abbreviation: 'VAN',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
}

export default teams
