const teams = [
  {
    teamID: 18,
    label: 'Atlanta Inferno',
    city: 'Atlanta',
    team: 'Inferno',
    abbreviation: 'ATL',
    league: 'SHL',
    conference: 'East',
  },
  {
    teamID: 7,
    label: 'Baltimore Platoon',
    city: 'Baltimore',
    team: 'Platoon',
    abbreviation: 'BAL',
    league: 'SHL',
    conference: 'East',
  },
  {
    teamID: 0,
    label: 'Buffalo Stampede',
    city: 'Buffalo',
    team: 'Stampede',
    abbreviation: 'BUF',
    league: 'SHL',
    conference: 'East',
  },
  {
    teamID: 1,
    label: 'Chicago Syndicate',
    city: 'Chicago',
    team: 'Syndicate',
    abbreviation: 'CHI',
    league: 'SHL',
    conference: 'East',
  },
  {
    teamID: 2,
    label: 'Hamilton Steelhawks',
    city: 'Hamilton',
    team: 'Steelhawks',
    abbreviation: 'HAM',
    league: 'SHL',
    conference: 'East',
  },
  {
    teamID: 4,
    label: 'Manhattan Rage',
    city: 'Manhattan',
    team: 'Rage',
    abbreviation: 'MAN',
    league: 'SHL',
    conference: 'East',
  },
  {
    teamID: 5,
    label: 'New England Wolfpack',
    city: 'New England',
    team: 'Wolfpack',
    abbreviation: 'NEW',
    league: 'SHL',
    conference: 'East',
  },
  {
    teamID: 6,
    label: 'Tampa Bay Barracudua',
    city: 'Tampa Bay',
    team: 'Barracudua',
    abbreviation: 'TBB',
    league: 'SHL',
    conference: 'East',
  },
  {
    teamID: 3,
    label: 'Toronto North Stars',
    city: 'Toronto',
    team: 'North Stars',
    abbreviation: 'TOR',
    league: 'SHL',
    conference: 'East',
  },
  {
    teamID: 8,
    label: 'Calgary Dragons',
    city: 'Calgary',
    team: 'Dragons',
    abbreviation: 'CAL',
    league: 'SHL',
    conference: 'West',
  },
  {
    teamID: 9,
    label: 'Edmonton Blizzard',
    city: 'Edmonton',
    team: 'Blizzard',
    abbreviation: 'EDM',
    league: 'SHL',
    conference: 'West',
  },
  {
    teamID: 13,
    label: 'Los Angeles Panthers',
    city: 'Los Angeles',
    team: 'Panthers',
    abbreviation: 'LAP',
    league: 'SHL',
    conference: 'West',
  },
  {
    teamID: 10,
    label: 'Minnesota Monarchs',
    city: 'Minnesota',
    team: 'Monarchs',
    abbreviation: 'MIN',
    league: 'SHL',
    conference: 'West',
  },
  {
    teamID: 14,
    label: 'New Orleans Specters',
    city: 'New Orleans',
    team: 'Specters',
    abbreviation: 'NOLA',
    league: 'SHL',
    conference: 'West',
  },
  {
    teamID: 12,
    label: 'San Francisco Pride',
    city: 'San Francisco',
    team: 'Pride',
    abbreviation: 'SFP',
    league: 'SHL',
    conference: 'West',
  },
  {
    teamID: 19,
    label: 'Seattle Argonauts',
    city: 'Seattle',
    team: 'Argonauts',
    abbreviation: 'SEA',
    league: 'SHL',
    conference: 'West',
  },
  {
    teamID: 15,
    label: 'Texas Renegades',
    city: 'Texas',
    team: 'Renegades',
    abbreviation: 'TEX',
    league: 'SHL',
    conference: 'West',
  },
  {
    teamID: 11,
    label: 'Winnipeg Aurora',
    city: 'Winnipeg',
    team: 'Aurora',
    abbreviation: 'WPG',
    league: 'SHL',
    conference: 'West',
  },
  {
    teamID: 21,
    label: 'Philadelphia Forge',
    city: 'Philadelphia',
    team: 'Forge',
    abbreviation: 'PHI',
    league: 'SHL',
    conference: 'East',
  },
  {
    teamID: 20,
    label: 'Montreal Patriotes',
    city: 'Montreal',
    team: 'Patriotes',
    abbreviation: 'MTL',
    league: 'SHL',
    conference: 'East',
  },
]

export default teams
