const teams = {
  Atlanta: {
    teamID: 18,
    label: 'Atlanta Inferno',
    city: 'Atlanta',
    team: 'Inferno',
    abbreviation: 'ATL',
    league: 'SHL',
    conference: 'East',
  },
  Baltimore: {
    teamID: 7,
    label: 'Baltimore Platoon',
    city: 'Baltimore',
    team: 'Platoon',
    abbreviation: 'BAL',
    league: 'SHL',
    conference: 'East',
  },
  Buffalo: {
    teamID: 0,
    label: 'Buffalo Stampede',
    city: 'Buffalo',
    team: 'Stampede',
    abbreviation: 'BUF',
    league: 'SHL',
    conference: 'East',
  },
  Chicago: {
    teamID: 1,
    label: 'Chicago Syndicate',
    city: 'Chicago',
    team: 'Syndicate',
    abbreviation: 'CHI',
    league: 'SHL',
    conference: 'East',
  },
  Hamilton: {
    teamID: 2,
    label: 'Hamilton Steelhawks',
    city: 'Hamilton',
    team: 'Steelhawks',
    abbreviation: 'HAM',
    league: 'SHL',
    conference: 'East',
  },
  Manhattan: {
    teamID: 4,
    label: 'Manhattan Rage',
    city: 'Manhattan',
    team: 'Rage',
    abbreviation: 'MAN',
    league: 'SHL',
    conference: 'East',
  },
  NewEngland: {
    teamID: 5,
    label: 'New England Wolfpack',
    city: 'New England',
    team: 'Wolfpack',
    abbreviation: 'NEW',
    league: 'SHL',
    conference: 'East',
  },
  TampaBay: {
    teamID: 6,
    label: 'Tampa Bay Barracudua',
    city: 'Tampa Bay',
    team: 'Barracudua',
    abbreviation: 'TBB',
    league: 'SHL',
    conference: 'East',
  },
  Toronto: {
    teamID: 3,
    label: 'Toronto North Stars',
    city: 'Toronto',
    team: 'North Stars',
    abbreviation: 'TOR',
    league: 'SHL',
    conference: 'East',
  },
  Calgary: {
    teamID: 8,
    label: 'Calgary Dragons',
    city: 'Calgary',
    team: 'Dragons',
    abbreviation: 'CAL',
    league: 'SHL',
    conference: 'West',
  },
  Edmonton: {
    teamID: 9,
    label: 'Edmonton Blizzard',
    city: 'Edmonton',
    team: 'Blizzard',
    abbreviation: 'EDM',
    league: 'SHL',
    conference: 'West',
  },
  LosAngeles: {
    teamID: 13,
    label: 'Los Angeles Panthers',
    city: 'Los Angeles',
    team: 'Panthers',
    abbreviation: 'LAP',
    league: 'SHL',
    conference: 'West',
  },
  Minnesota: {
    teamID: 10,
    label: 'Minnesota Monarchs',
    city: 'Minnesota',
    team: 'Monarchs',
    abbreviation: 'MIN',
    league: 'SHL',
    conference: 'West',
  },
  NewOrleans: {
    teamID: 14,
    label: 'New Orleans Specters',
    city: 'New Orleans',
    team: 'Specters',
    abbreviation: 'NOLA',
    league: 'SHL',
    conference: 'West',
  },
  SanFrancisco: {
    teamID: 12,
    label: 'San Francisco Pride',
    city: 'San Francisco',
    team: 'Pride',
    abbreviation: 'SFP',
    league: 'SHL',
    conference: 'West',
  },
  Seattle: {
    teamID: 19,
    label: 'Seattle Argonauts',
    city: 'Seattle',
    team: 'Argonauts',
    abbreviation: 'SEA',
    league: 'SHL',
    conference: 'West',
  },
  Texas: {
    teamID: 15,
    label: 'Texas Renegades',
    city: 'Texas',
    team: 'Renegades',
    abbreviation: 'TEX',
    league: 'SHL',
    conference: 'West',
  },
  Winnipeg: {
    teamID: 11,
    label: 'Winnipeg Aurora',
    city: 'Winnipeg',
    team: 'Aurora',
    abbreviation: 'WPG',
    league: 'SHL',
    conference: 'West',
  },
  Anaheim: {
    teamID: 5,
    label: 'Anaheim Outlaws',
    city: 'Anaheim',
    team: 'Outlaws',
    abbreviation: 'ANA',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  Anchorage: {
    teamID: 0,
    label: 'Anchorage Armada',
    city: 'Anchorage',
    team: 'Armada',
    abbreviation: 'ANC',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  Carolina: {
    teamID: 9,
    label: 'Carolina Kraken',
    city: 'Carolina',
    team: 'Kraken',
    abbreviation: 'CAR',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  Colorado: {
    teamID: 6,
    label: 'Colorado Raptors',
    city: 'Colorado',
    team: 'Raptors',
    abbreviation: 'COL',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  Detroit: {
    teamID: 7,
    label: 'Detroit Falcons',
    city: 'Detroit',
    team: 'Falcons',
    abbreviation: 'DET',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  Kelowna: {
    teamID: 1,
    label: 'Kelowna Knights',
    city: 'Kelowna',
    team: 'Knights',
    abbreviation: 'KEL',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  Maine: {
    teamID: 2,
    label: 'Maine Timber',
    city: 'Maine',
    team: 'Timber',
    abbreviation: 'MET',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  Nevada: {
    teamID: 14,
    label: 'Nevada Battleborn',
    city: 'Nevada',
    team: 'Battleborn',
    abbreviation: 'NBB',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  Newfoundland: {
    teamID: 4,
    label: 'Newfoundland Berserkers',
    city: 'Newfoundland',
    team: 'Berserkers',
    abbreviation: 'NL',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  QuebecCity: {
    teamID: 15,
    label: 'Quebec City Citadelles',
    city: 'Quebec City',
    team: 'Citadelles',
    abbreviation: 'QCC',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  StLouis: {
    teamID: 8,
    label: 'St. Louis Scarecrows',
    city: 'St. Louis',
    team: 'Scarecrows',
    abbreviation: 'STL',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  Vancouver: {
    teamID: 3,
    label: 'Vancouver Whalers',
    city: 'Vancouver',
    team: 'Whalers',
    abbreviation: 'VAN',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  Philadelphia: {
    teamID: 21,
    label: 'Philadelphia Forge',
    city: 'Philadelphia',
    team: 'Forge',
    abbreviation: 'PHI',
    league: 'SHL',
    conference: 'East',
  },
  Montreal: {
    teamID: 20,
    label: 'Montreal Patriotes',
    city: 'Montreal',
    team: 'Patriotes',
    abbreviation: 'MTL',
    league: 'SHL',
    conference: 'East',
  },
  GreatFalls: {
    teamID: 17,
    label: 'Great Falls Grizzles',
    city: 'Great Falls',
    team: 'Grizzles',
    abbreviation: 'GFG',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
  Regina: {
    teamID: 16,
    label: 'Regina Elk',
    city: 'Regina',
    team: 'Elk',
    abbreviation: 'REG',
    league: 'SMJHL',
    conference: 'SMJHL',
  },
}

export default teams
